services:
  app:
    image: node:12-alpine
    user: node
    working_dir: /home/node/app
    command: yarn run serve
    volumes:
      - ./:/home/node/app:rw
    expose:
      - 8080
    labels:
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-app.service=${COMPOSE_PROJECT_NAME:??}-app"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME:??}-app.loadbalancer.passhostheader=false"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME:??}-app.loadbalancer.server.port=8080"
