services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME:??}-app
    restart: unless-stopped
    build:
      args:
        VUE_APP_STARC_WEBAPI_URL: ${VUE_APP_STARC_WEBAPI_URL:-http://localhost:8090}
        VUE_APP_STARC_STATIC_URL: ${VUE_APP_STARC_STATIC_URL:-http://localhost:8090}
        VUE_APP_STARC_BATTLE_API_CLIENT_ID: ${VUE_APP_STARC_BATTLE_API_CLIENT_ID:??}
    environment:
      VUE_APP_STARC_WEBAPI_URL: ${VUE_APP_STARC_WEBAPI_URL:-http://localhost:8090}
      VUE_APP_STARC_STATIC_URL: ${VUE_APP_STARC_STATIC_URL:-http://localhost:8090}
      VUE_APP_STARC_BATTLE_API_CLIENT_ID: ${VUE_APP_STARC_BATTLE_API_CLIENT_ID:??}
    networks:
      - webproxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=webproxy"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-app.rule=Host(`$APP_HOST`, `www.$APP_HOST`) && (!PathPrefix(`/api`) && !PathPrefix(`/static`))"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-app.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:??}-app.tls=true"

networks:
  webproxy:
    name: webproxy
    external: true
